apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-creator-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: azure-function-sa
  namespace: default
roleRef:
  kind: Role
  name: deployment-creator-role
  apiGroup: rbac.authorization.k8s.io
