name: Build and deploy container image to Azure Container Registry - sihir_interview_fe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: sihirimage.azurecr.io
        username: SihirImage
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sihirimage.azurecr.io/sihir_interview_fe:latest
        file: ./Dockerfile
